---
# tasks file for /etc/ansible/roles/docker
- name: Ensure old versions of Docker are not installed.
  package:
     name:
      - docker
      - docker-engine
     state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
- name: add Docker GpG
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repository.
  apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
  state: present
  update_cache: true

- name: install docker
  apt: name=docker-ce state=latest
  notify:
  - restart docker

- name: create docker group
  group: name=docker gid=2002 state=present

- name: add ubunto to docker group
  user: name=ubuntu group=docker append=yes
